services:
  - type: web
    name: adega-api
    plan: free
    runtime: docker
    rootDir: api
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: ConnectionStrings__DefaultConnection
        value: "Host=ep-rapid-forest-ams8xemm-pooler.c-5.us-east-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_OwuCLEAoh9G5;SslMode=Require;Trust Server Certificate=true;"
      - key: Jwt__Issuer
        value: AdegaRoyal
      - key: Jwt__Audience
        value: AdegaRoyalClient
      - key: Jwt__SecretKey
        value: "ad73a326-5687-4684-8d45-2b9641e0715e-b75c5aab-2dc5-4906-8dc4-3253d3e6dd89" 
      - key: Jwt__ExpiryInMinutes
        value: "60"