services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adega-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__DefaultConnection=postgresql://neondb_owner:npg_OwuCLEAoh9G5@ep-rapid-forest-ams8xemm-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    ports:
      - "8000:8000"
    networks:
      - adega-network

networks:
  adega-network:
    driver: bridge